# Configuración de comandos de escaneo
scan_commands:
  nmap:
    command: "nmap -sV -T4 {target}"
    description: "Escaneo básico de puertos y servicios"
    enabled: true
    parser: "nmap"
    timeout: 60

  nikto:
    command: "nikto -h {target}"
    description: "Escaneo de vulnerabilidades web"
    enabled: true
    parser: "nikto"
    timeout: null

  dirb:
    command: "dirb http://{target} -S -w /usr/share/wordlists/dirb/common.txt"
    description: "Búsqueda de directorios web"
    enabled: true
    parser: "dirb"
    timeout: null

  nmap_extended:
    command: "nmap -sV --script vuln {target}"
    description: "Escaneo de puertos y vulnerabilidades con Nmap (scripts vuln)"
    enabled: true
    parser: "nmap_extended"
    timeout: null

# Perfiles de escaneo
scan_profiles:
  rapido:
    - nmap

  completo:
    - nikto
    - dirb
    - nmap_extended
  
  web:
    - nikto
    - dirb

# Configuración general
general:
  timeout: 15  # Tiempo máximo de espera por comando en segundos
  output_format: "json"  # Formato de salida por defecto
  parse_results: true  # Activar/desactivar parseo de resultados 
