# Configuración de comandos de escaneo
scan_commands:
  ping:
    command: "ping -n 4 {target}"
    description: "Prueba de conectividad básica"
    enabled: true
    parser: "ping"
    timeout: 10
  
  nmap_basic:
    command: "nmap -sV -T4 {target}"
    description: "Escaneo básico de puertos y servicios"
    enabled: true
    parser: "nmap"
    timeout: 60
  
  whois:
    command: "whois {target}"
    description: "Información de registro WHOIS"
    enabled: true
    parser: "whois"

  nikto:
    command: "nikto -h {target} -Format txt"
    description: "Escaneo de vulnerabilidades web"
    enabled: true
    parser: "nikto"

  dirb:
    command: "dirb http://{target} -S"
    description: "Búsqueda de directorios web"
    enabled: true
    parser: "dirb"

  sslscan:
    command: "sslscan {target}"
    description: "Análisis de configuración SSL/TLS"
    enabled: true
    parser: "sslscan"

  nmap_extended:
    command: "nmap -sV --script vuln {target}"
    description: "Escaneo de puertos y vulnerabilidades con Nmap (scripts vuln)"
    enabled: true
    parser: "nmap_extended"
    timeout: null

# Perfiles de escaneo
scan_profiles:
  rapido:
    - ping
    - nmap_basic
  
  completo:
    - ping
    - nmap_basic
    - whois
    - nikto
    - sslscan
  
  web:
    - nikto
    - dirb
    - sslscan

# Configuración general
general:
  timeout: 15  # Tiempo máximo de espera por comando en segundos
  output_format: "json"  # Formato de salida por defecto
  parse_results: true  # Activar/desactivar parseo de resultados 
